### ISSUE TITLE
No icon in Tray Gnome 42

### ISSUE THREAD

**Issue by serossi** [coldfix/steam-acolyte#12]
OS pop!os 22.04 LTS
running X11 (not wayland)

so far it works, when closing steam it comes up in front. but there is no tray icon ever. it did work in 21.10/gnome i think 40

**Comment by coldfix** [comment]
Hey, thanks for the info. I'll try to check up on this later this week.

I'm not too much surprised with the rate at which the gnome devs remove all useful things to be honest lol.

**Comment by coldfix** [comment]
sorry, I completely forgot about this, but I have now checked into this. It seems gnome has finally removed status icons.

https://support.system76.com/articles/status-icons/

Don't think there is anything I can do about it. I recommend migrating to a different desktop environment. gnome has gradually been trying to remove all useful features for a long time.

**Comment by coldfix** [comment]
Closing this. Let me know if you think it's due to a different reason or something can be done about it.

**Comment by serossi** [comment]
well as far i understand they just removed legacy compatibility not icons in general. 
i have plenty of apps running with status icons, just i assume on an updated api. i just never did anything with these kind of apis so cant tell how much effort compatibility would be

btw pop!os gonna switch its DE soon to their own new shiny completly rewritten DE in rust. most other DEs are just gnome or kde forks so gonna be interresting

**Comment by coldfix** [comment]
I guess so and I'm open to accepting PRs supporting replacement APIs, but I probably won't work on it on my own. For me gnome is dead.

In the linked blogpost they basically write they don't care that applications will break because they think that applications overuse the status bar. Effectively, instead of providing wrapper for what they declared "legacy" icons that the user can enable on their chosing, they put the responsibility on the individual applications to update their code if they still believe a status icon is useful, which -of course- applies to basically every application that previously had a status icon (because why would you just add that if you don't think it's useful, and why would users install these applications if they are annoyed by all the status icons). And after plenty of unnecessary work done on all ends we will be in the same situation as before and they will again deprecate their APIs because they think applications shouldn't use it. It's the same story over and over again with gnome.
