### ISSUE TITLE
steam-acolyte never shutting down

### ISSUE THREAD

**Issue by veganvelociraptor** [coldfix/steam-acolyte#6]
When I close down the steam-acolyte window, after shutting down Steam, the process keeps running in the background preventing me from restarting it again.

Is this a bug or a feature? :-)

**Comment by coldfix** [comment]
Hi,

thanks for reporting the issue. I have recently fixed a similar issue, so first let me know which version of acolyte you are using (`steam-acolyte --version`) and on which operating system?

If your version is below 0.7.2, please upgrade and let me know if the issue still occurs.

If you are already on 0.7.2: The acolyte process will keep running as long as steam is running (otherwise it might terminate steam with itself if steam was started as a subprocess), so this is expected if for any reason steam was still running longer than expected.

If acolyte "outlives" steam in the background, it is another bug that is likely due to fragility of the implemented single-instance-lock. In this case, let's start collecting clues by collecting some debug output while this issue is happening, using the following command:

```
steam-acolyte -l steam.log -v | tee acolyte.log
```

**Comment by coldfix** [comment]
@veganvelociraptor Did you get the message?

**Comment by veganvelociraptor** [comment]
Yep, I'll get back once I have time to look it up.

**Comment by coldfix** [comment]
Oups, I justed wanted to check back on this issue and realized I had already closed it somehow. Anyway, if this still occurs on the latest version, let me know, otherwise I assume it was likely the bug I had fixed a few days before your report.
