### ISSUE TITLE
Tray Icon doesn't show

### ISSUE THREAD

**Issue by Curve** [coldfix/steam-acolyte#8]
When installing the `steam-acolyte` aur package the tray icon is invisible.
![image](https://user-images.githubusercontent.com/37805707/106355313-4a6c7c80-62f7-11eb-85a1-b80cdee071cd.png)
![image](https://user-images.githubusercontent.com/37805707/106355328-6b34d200-62f7-11eb-88d7-00a4aac6d451.png)

**Comment by coldfix** [comment]
Interesting. What OS and desktop is this?

**Comment by Curve** [comment]
Oh sorry forgot to mention, Arch Linux & KDE

**Comment by coldfix** [comment]
Ok. I can reproduce the issue. Weirdly, it occurs only with the AUR package, but works as expected if installing with `pip`.

I already checked the icon file is included in the AUR package and found and loaded by the application. I'll need some more time to figure out what's going on there.

**Comment by coldfix** [comment]
I have a workaround to make the tray icon appear, by converting the `theme.window_icon` to a `QPixmap` and then converting again to `QIcon` before passing it to the `QSystemTrayIcon`, i.e.:

```diff
- self.trayicon = QSystemTrayIcon(self.theme.window_icon)
+ self.trayicon = QSystemTrayIcon(QIcon(self.theme.window_icon.pixmap(32)))
```

But I've still got no clue why this is happening and especially why only for the system-installed package.

The window icon (which uses the very same icon) is displayed correctly by the AUR package without this workaround. And it's no resource-sharing problem either, since the problem also occurs if the tray gets its own QIcon instance of the file.

I also checked that AUR and pip have installed identical code/svg files, and that python and even pyqt version is the same between the two. So, no clue really.

I can fix it with the workaround for the next version, but I'd still like to know why this is happening.

**Comment by coldfix** [comment]
FYI: possibly related issue https://bugreports.qt.io/browse/QTBUG-53550
